services:
  oracle:
    image: gvenzl/oracle-free:latest
    container_name: crm-project-oracle-small
    ports:
      - "1522:1522"
    environment:
      - ORACLE_PASSWORD=${ORACLE_PWD}
      - APP_USER=${DB_USERNAME}
      - APP_USER_PASSWORD=${DB_PASSWORD}
    volumes:
      - oracle-data:/opt/oracle/oradata
volumes:
  oracle-data: