spring.application.name=crm
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.sql.init.mode=always
spring.sql.init.platform=oracle
spring.sql.init.separator=/

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.docker.compose.readiness.timeout=5m
spring.docker.compose.readiness.wait=always

logging.file.name=logs/crm-app.log
logging.logback.rollingpolicy.max-history=30

crm.security.self=${SELF}
crm.security.jwt-secret=${JWT_SECRET}
crm.security.hashid_salt=${HASHID_SALT}
crm.security.hashid_length=${HASHID_LENGTH}
crm.security.hashid_alphabet=${HASHID_ALPHABET}